name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to publish (patch, minor, major, or specific version)
        required: true
        default: patch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    environment:
      name: publish

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci
      - run: npm run build
      - run: npm run test

      - run: npm version ${{ github.event.inputs.version }} --allow-same-version
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - run: git push origin main --tags
